# Generated by Django 5.1.2 on 2024-11-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('undergrad_course', models.CharField(max_length=100)),
                ('undergrad_school', models.CharField(max_length=100)),
                ('undergrad_award', models.CharField(max_length=100)),
                ('undergrad_scholarship', models.CharField(max_length=100)),
                ('postgrad_course', models.CharField(max_length=100)),
                ('postgrad_school', models.CharField(max_length=100)),
                ('postgrad_award', models.CharField(max_length=100)),
                ('postgrad_scholarship', models.CharField(max_length=100)),
                ('other_achievments', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
