# Generated by Django 5.1.2 on 2024-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='honorary_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='suffix',
            field=models.CharField(max_length=50),
        ),
    ]
