# Generated by Django 5.1.2 on 2024-11-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='honorary_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='suffix',
            field=models.CharField(max_length=20),
        ),
    ]
