# Generated by Django 5.1.2 on 2024-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0003_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='honorary_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
