# Generated by Django 5.1.2 on 2024-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0006_alter_instructor_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
