# Generated by Django 5.1.2 on 2024-12-02 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0008_committee_committeemember_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='committee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crmwebsite.committee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
