# Generated by Django 5.1.2 on 2024-12-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0010_remove_task_committee_alter_task_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
